#!/usr/bin/perl -w

use strict;

#my @IPprefix=("192.168.200","172.16.1");
my $prefix;
my ($host, %message, %rc);
foreach my $argnum (0 .. $#ARGV) {
	if ($ARGV[$argnum] =~ /^-H(.+)$/i) {
		$host=$1;
	} elsif ($ARGV[$argnum] =~ /^-H$/i) {
		$argnum++;
		$host= $ARGV[$argnum]
	}
}

if ($host =~ /^192/g ) {
	$host=~ s/192\.168\.200\.//;
	$prefix = "192.168.200";
		} elsif ($host =~ /^172/g) {
			if ($host =~ /172\.16\.1/) {
				$host=~ s/172\.16\.1\.//;
				$prefix = "172.16.1";
					       } elsif ($host =~ /172\.16\.3/) {
					         	   $host=~ s/172\.16\.3\.//;
							   $prefix = "172.16.3";
									      } elsif ($host =~ /172\.16\.4/g) {
												$host=~ s/172\.16\.4\.//;
												$prefix = "172.16.4";
													}
						    } 
#$host=~ s/172\.16\.3\.//;
#$host=~ s/172\.16\.4\.//;


#foreach my $prefix (@IPprefix) {

	open(PRG,"/usr/local/nagios/libexec/check_ping -H $prefix.$host -w 3000.0,80% -c 5000.0,100% -p 1|");
	$message{$prefix.$host}=<PRG>;
	chomp $message{$prefix.$host};
	$message{$prefix.$host} =~ s/-/-$prefix.$host-/;
	if (close(PRG)) {
		$rc{$prefix.$host}=$?;
	} else {
		$rc{$prefix.$host}=2;
	}
#}


my $rmessage="";
my $exit_code=0;
foreach $host (sort {$rc{$b} <=> $rc{$a} } keys %rc) {
	$rmessage .= $message{$host} . " ";
	$exit_code=$rc{$host} if ($exit_code < $rc{$host});
}

$rmessage =~ s/ *$//;

print "$rmessage\n";
exit $exit_code;

